namespace CodeAnalysis;

public enum SyntaxKind
{
    Token_Error,
    Token_Discard,
    Token_End,
    Token_InvalidChar,
    Token_Space,
    Token_CommentMarker,
    Token_Comment,

    Token_Indent,
    Token_BeginBlock,
    Token_EndBlock,
    Token_NewLine,
    Token_Number,
    Token_StringMarker,
    Token_String,
    Token_Identifier,
    // Token_UnusedIdentifier,

    Token_LParen,
    Token_RParen,
    Token_LSquare,
    Token_RSquare,

    Token_Dot,
    Token_Comma,
    Token_Colon,
    Token_Semicolon,
    Token_RArrow,

    Token_Plus,
    Token_Minus,
    Token_Star,
    Token_Slash,

    Token_Less,
    Token_Greater,
    Token_Equal,
    Token_Percent,

    // Token_LBrace,
    // Token_RBrace,
    Token_EqualEqual,
    Token_NotEqual,
    Token_LessEqual,
    Token_GreaterEqual,

    Token_PlusPlus,
    Token_PlusEqual,
    Token_MinusMinus,
    Token_MinusEqual,
    Token_StarEqual,
    Token_SlashEqual,
    Token_PercentEqual,

    Keyword_Public,
    Keyword_Static,
    Keyword_Abstract,
    Keyword_Section,
    Keyword_Struct,
    Keyword_Include,
    Keyword_Function,
    Keyword_Mut,
    Keyword_Var,
    Keyword_If,
    Keyword_Else,
    Keyword_Switch,
    Keyword_For,
    Keyword_Do,
    Keyword_While,

    Keyword_Int,
    Keyword_UInt,
    Keyword_Float,
    Keyword_Number,
    // Keyword_Char,
    // Keyword_String,

    Syntax_Empty,
    Syntax_Error,

    Syntax_DeclarationStatement,
    Syntax_TypeClause,

    Syntax_Addition,
    Syntax_Subtraction,
    Syntax_Multiplication,
    Syntax_Division,
    Syntax_CompilationUnit,
}
